deployments:
- build_id: 516cb46c-5561-4d26-9aa0-56fcb3d2608f
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T15:52:34.089510'
  deployment_id: 1b1ad59f-efd1-4b2e-9c2f-593d8c4755df
  image: jhnnsrs/omero:0.0.1
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T15:52:19.155821'
    entrypoint: app
    identifier: omero
    requirements: []
    scopes:
    - read
    version: 0.0.1
- build_id: b84ec7f0-c4b6-45ad-9a06-475ed555ea88
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T17:13:12.641266'
  deployment_id: 1edc9e8d-7958-46e8-b903-5e7f034a21de
  image: jhnnsrs/omero:0.0.2
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T17:12:56.137567'
    entrypoint: app
    identifier: omero
    requirements: []
    scopes:
    - read
    version: 0.0.2
latest_deployment: '2023-08-29T17:13:12.642558'
